title: "Feiqing (Amiee) Huang"
url: "https://avocada.github.io"
baseurl: ""
navbar_fixed: true
footer_fixed: true
search_enabled: true
max_width: 930px

plugins:
  - jekyll-toc
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  source: _bibliography
  bibliography: papers.bib
  bibliography_template: bib
  query: "@*"
  group_by: topic          # <- group sections by topic
  group_order: ascending   # A→Z; (use 'descending' if you prefer Z→A)
  sort_by: year            # <- inside each topic, sort by year
  order: descending        # newest first

collections:
  projects:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"

include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
  - _pages/blog.md
  - _pages/cv.md
  - _pages/dropdown.md
  - _pages/news.md
  - _pages/profiles.md
  - _pages/repositories.md
  - _pages/teaching.md

keep_files: [CNAME, .nojekyll]

sass:
  style: compressed

# optional UI toggles you were using (safe to keep)
enable_darkmode: true
enable_masonry: true
enable_medium_zoom: true
enable_progressbar: true
